import '../app/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/componenets/header';
import HeaderMobile from '@/componenets/header-mobile';
import MarginWidthWrapper from '@/componenets/margin-width-wrapper';
import PageWrapper from '@/componenets/page-wrapper';
import SideNav from '@/componenets/side-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MoreBobaPlease',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`flex-col w:1/10 bg-white${inter.className}`}>
        <div className="flex">
          <SideNav />
          <main className="mx-auto">
            <MarginWidthWrapper>
              <Header />
              {/* <HeaderMobile /> */}
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}