extend type Query {
  """
  Look up a single Admin based on `id` or `key` and return selected fields (or `null` if not found).
  """
  admin(key: Admin_Key): Admin
  """
  Look up a single Cart based on `id` or `key` and return selected fields (or `null` if not found).
  """
  cart(id: UUID, key: Cart_Key): Cart
  """
  Look up a single Item based on `id` or `key` and return selected fields (or `null` if not found).
  """
  item(key: Item_Key): Item
  """
  Look up a single Section based on `id` or `key` and return selected fields (or `null` if not found).
  """
  section(key: Section_Key): Section
  """
  List Admin entries in the table, optionally filtered by `where` conditions.
  """
  admins(where: Admin_Filter, orderBy: [Admin_Order!], limit: Int = 100): [Admin!]!
  """
  List Cart entries in the table, optionally filtered by `where` conditions.
  """
  carts(where: Cart_Filter, orderBy: [Cart_Order!], limit: Int = 100): [Cart!]!
  """
  List Item entries in the table, optionally filtered by `where` conditions.
  """
  items(where: Item_Filter, orderBy: [Item_Order!], limit: Int = 100): [Item!]!
  """
  List Section entries in the table, optionally filtered by `where` conditions.
  """
  sections(where: Section_Filter, orderBy: [Section_Order!], limit: Int = 100): [Section!]!
}
